import { GoogleGenAI } from "@google/genai";
import { ImageGenerationProvider, ImageGenerationRequest, GeneratedImage } from "./image-provider";
import { storeImage, fetchReferenceBytes } from "./image-storage";
import { VertexConfig, vertexClientOptions } from "./vertex-provider";
import { withRetry } from "./retry";

export class VertexImageProvider implements ImageGenerationProvider {
  name = "vertex";
  defaultModel: string;
  supportsReferences = true;
  private client: GoogleGenAI;
  private perImageCost: number;

  constructor(cfg: VertexConfig) {
    this.client = new GoogleGenAI(vertexClientOptions(cfg));
    this.defaultModel = process.env.VERTEX_IMAGE_MODEL ?? "gemini-2.5-flash-image";
    this.perImageCost = parseFloat(process.env.VERTEX_IMAGE_COST_USD ?? "0.039");
  }

  estimateCost(): number {
    return this.perImageCost;
  }

  async generate(req: ImageGenerationRequest): Promise<GeneratedImage> {
    const t0 = Date.now();
    const parts: any[] = [{ text: composeForFrame(req.prompt, req.width, req.height) }];
    if (req.references?.length) {
      for (const ref of req.references.slice(0, 2)) {
        const buf = await fetchReferenceBytes(ref);
        if (buf) parts.push({ inlineData: { mimeType: "image/png", data: buf.toString("base64") } });
      }
    }

    const response = await withRetry(
    () =>
    this.client.models.generateContent({
      model: this.defaultModel,
      contents: [{ role: "user", parts }],
      config: { responseModalities: ["TEXT", "IMAGE"] } as any,
    }),
    { label: "VERTEX-IMAGE", retries: 4, baseDelayMs: 8000 }
    );

    const respParts: any[] = response.candidates?.[0]?.content?.parts ?? [];
    const imagePart = respParts.find((p) => p.inlineData?.data);
    if (!imagePart) {
      const text = respParts.map((p) => p.text).filter(Boolean).join(" ").slice(0, 300);
      const blockReason =
        (response as any).promptFeedback?.blockReason ??
        (response as any).candidates?.[0]?.finishReason ??
        "";
      console.error("[VERTEX-IMAGE] No image in response.", "blockReason:", blockReason, "| model said:", text);
      throw new Error(
        `[VERTEX-IMAGE] Model returned no image${blockReason ? ` (${blockReason})` : ""}${text ? `: ${text}` : ""}`
      );
    }

    const raw = Buffer.from(imagePart.inlineData.data, "base64");
    const mimeType = imagePart.inlineData.mimeType ?? "image/png";

    // Gemini returns its own fixed size (typically 1024×1024) regardless of what was asked for.
    // We used to store that and then *report* req.width/req.height anyway, so a "1280×720 YouTube
    // thumbnail" was a square file with lying metadata — and the product's own promise of exact
    // pixels for every platform was untrue. Fit to the requested frame before storing.
    const { bytes, width, height } = await fitToRequestedSize(raw, req.width, req.height);
    const uri = await storeImage(bytes, mimeType);

    return {
      provider: "vertex",
      model: this.defaultModel,
      uri,
      width: width ?? req.width,
      height: height ?? req.height,
      seed: req.seed,
      latencyMs: Date.now() - t0,
      costUSD: this.perImageCost,
      requestId: `vertex-${Date.now()}`,
      promptUsed: req.prompt,
      supportsReferences: true,
      referencesUsed: req.references,
    };
  }
}

/**
 * Resize generated bytes to the frame the caller asked for.
 *
 * Cover-crops rather than letterboxing, so a 16:9 thumbnail is a full-bleed 16:9 image instead of
 * a square with bars. Falls back to the original bytes if sharp cannot read them — a wrong-sized
 * image beats no image, and the reported dimensions then describe what is actually stored.
 */
async function fitToRequestedSize(
  raw: Buffer,
  width?: number,
  height?: number
): Promise<{ bytes: Buffer; width?: number; height?: number }> {
  if (!width || !height) return { bytes: raw, width, height };
  try {
    const sharp = (await import("sharp")).default;
    const meta = await sharp(raw).metadata();
    if (meta.width === width && meta.height === height) return { bytes: raw, width, height };
    const bytes = await sharp(raw).resize(width, height, { fit: "cover", position: "attention" }).png().toBuffer();
    return { bytes, width, height };
  } catch (e) {
    console.error("[VERTEX-IMAGE] resize failed, storing original:", e);
    try {
      const sharp = (await import("sharp")).default;
      const meta = await sharp(raw).metadata();
      return { bytes: raw, width: meta.width, height: meta.height };
    } catch {
      return { bytes: raw, width: undefined, height: undefined };
    }
  }
}

/**
 * Ask the model to compose for the target frame.
 *
 * Gemini returns a square whatever we request, and the resize step then cover-crops it to the
 * asked-for shape. For a 16:9 thumbnail that is harmless, but a LinkedIn banner is nearly 6:1 —
 * cropping a square to that keeps a thin horizontal band and throws the subject away. Telling the
 * model the shape up front gets a composition that survives the crop: subject centred on the long
 * axis, headroom where the crop will bite.
 */
function composeForFrame(prompt: string, width?: number, height?: number): string {
  if (!width || !height) return prompt;
  const ratio = width / height;
  if (ratio > 0.95 && ratio < 1.05) return prompt;   // square needs no guidance

  const shape =
    ratio >= 3 ? "an extremely wide panoramic banner"
    : ratio >= 1.6 ? "a wide landscape frame"
    : ratio > 1 ? "a landscape frame"
    : ratio <= 0.4 ? "an extremely tall vertical frame"
    : ratio <= 0.6 ? "a tall vertical frame"
    : "a portrait frame";

  return (
    `${prompt}\n\nCompose this for ${shape}, aspect ratio ${width}:${height}. ` +
    `Fill the entire frame edge to edge — no borders, no letterboxing, no blank or white margins. ` +
    `Keep the subject away from the ${ratio > 1 ? "top and bottom" : "left and right"} edges, ` +
    `since the image is cropped to that shape.`
  );
}
