/**
 * Real outputs, with the exact prompts that produced them.
 *
 * Every entry here was generated by this product through the tool it is filed under — nothing is
 * stock, and no prompt is reconstructed after the fact. That matters twice over: the gallery is
 * the proof that the tool is good, and clicking an example loads its real prompt into the field,
 * so the fastest way to learn what a good brief looks like is to run one.
 *
 * When adding entries: generate through the tool, keep the prompt verbatim, and check the result
 * carries no third-party trademark or real person's likeness before shipping it as marketing.
 *
 * Assets live in `public/showcase/` rather than the `.data/` runtime cache, which is gitignored —
 * served from there they would 404 on a fresh clone, which is exactly what a reviewer sees first.
 * They are re-encoded for the web on the way in (PNG -> WebP, H.264 CRF 28), taking the showcase
 * set from 181 MB to 19 MB without a visible difference at display size.
 */
export interface ToolExample {
  uri: string;
  kind: "image" | "video" | "text" | "compare";
  /** The verbatim prompt. Omit only for assets whose original prompt isn't recoverable. */
  prompt?: string;
  /** Short label used when there is no prompt to show. */
  caption?: string;
  /** For kind "compare": the lower-resolution original the result is measured against. */
  before?: string;
  /** For kind "text": the output the tool produced from `uri`. */
  output?: string;
  /** True pixel dimensions. When present the tile is rendered at this exact ratio rather than
   *  being squared off — on a platform page the shape of a format is part of the information. */
  width?: number;
  height?: number;
}

export const TOOL_EXAMPLES: Record<string, ToolExample[]> = {
  t2i: [
    { uri: "/showcase/img-1787400342415-knx2au.webp", kind: "image", width: 1024, height: 1024, prompt: "A glass-blower turning a glowing orange gather of molten glass on the pipe, his lit face close in frame, sparks and dark workshop behind, warm firelight filling the whole frame edge to edge, no empty ceiling, cinematic" },
    { uri: "/showcase/img-1787399047430-f6i3c1.webp", kind: "image", width: 1280, height: 720, prompt: "An abandoned observatory dome open to a star-filled sky, moonlight through rusted machinery, wide cinematic shot" },
    { uri: "/showcase/img-1787399087596-ds07sn.webp", kind: "image", width: 1080, height: 1350, prompt: "A sushi chef's hands slicing toro on a hinoki counter, overhead, precise, natural light, portrait framing" },
    { uri: "/showcase/img-1787399154854-rgt5gb.webp", kind: "image", width: 1280, height: 720, prompt: "A vintage racing car mid-drift on a wet mountain road, spray and motion blur, golden hour, cinematic" },
    { uri: "/showcase/img-1787393434023-vuvget.webp", kind: "image", width: 1024, height: 1024, prompt: "Editorial portrait of a woman in a scarlet wool coat against a raw concrete wall, hard directional side light, deep shadow, no text" },
    { uri: "/showcase/img-1787393350826-y118uv.webp", kind: "image", width: 1024, height: 1024, prompt: "A lone astronaut planting a glowing flag on a crystal moon, vast starfield behind, epic scale, cinematic wide shot" },
    { uri: "/showcase/img-1787393219559-4laifg.webp", kind: "image", width: 1024, height: 1024, prompt: "Macro shot of morning dew on a spider web at golden hour, extreme shallow depth of field, backlit, nature photography" },
  ],

  // Its own before/after pairs — the sources here belong to no other tool, so nothing is reused.
  upscale: [
    { uri: "/showcase/img-1787400714242-x22yhe.webp", before: "/showcase/img-1787399199647-vtj78t.webp", kind: "compare", width: 1280, height: 1280, caption: "320×320 original, upscaled 4× to 1280×1280" },
  ],

  i2p: [
    {
      // The verbatim output of a real Decode run on this still — never a paraphrase, since the
      // whole point of the example is to show how good the description actually is.
      uri: "/showcase/img-1787393197957-wde7pa.webp",
      kind: "text",
      width: 1024,
      height: 1024,
      caption: "Read from this still",
      output:
        "A highly detailed cyberpunk city street corner at night in heavy rain, featuring a vibrant ramen shop. The scene is dominated by glowing neon signs in red, cyan, pink, and orange, casting intense reflections on the wet, shimmering street below. Several indistinct figures with umbrellas walk through the rain, while others sit at the ramen counter. Electrical wires crisscross overhead against dark futuristic buildings. Atmospheric rain streaks, misty steam, and a moody neo-noir ambiance.",
    },
  ],

  social: [
    { uri: "/showcase/img-1787393624459-a8oabp.webp", kind: "image", width: 1024, height: 1024, prompt: "Announcing our autumn drop: hand-thrown ceramic mugs, 40 pieces only, glazed in storm blue" },
  ],

  text: [
    { uri: "/showcase/img-1787399392315-9vhad4.webp", kind: "image", width: 1280, height: 720, caption: "A canvas composed with open sky for a headline" },
    { uri: "/showcase/img-1787399440644-ymou4o.webp", kind: "image", width: 1080, height: 1350, caption: "Fog in the upper third — type sits in the negative space" },
  ],

  cast: [
    { uri: "/showcase/img-1787397383335-x9bbd1.webp", kind: "image", width: 1024, height: 1024, prompt: "A weathered dockside fisherwoman in her sixties, silver braid, oilskin jacket, sun-creased face, warm and unsmiling" },
  ],

  t2v: [
    { uri: "/showcase/vid-1787374077992-3l6bin.mp4", kind: "video", width: 1280, height: 720, caption: "Golden-hour tracking shot" },
    { uri: "/showcase/vid-1787374178740-d2ulgs.mp4", kind: "video", width: 1280, height: 720, caption: "Drone rise over misty pine forest" },
  ],

  i2v: [
    { uri: "/showcase/vid-1787379851902-9jlkz4.mp4", kind: "video", width: 1280, height: 720, caption: "A still brought to life — molten metal in motion" },
  ],

  flow: [
    { uri: "/showcase/vid-1787379672761-hjfeyd.mp4", kind: "video", width: 1280, height: 720, caption: "Narration, references and direction in one pass" },
  ],

  ytkit: [
    { uri: "/showcase/vid-1787380605932-wc0u9d.mp4", kind: "video", width: 1280, height: 720, caption: "A finished short, cut and narrated" },
    { uri: "/showcase/img-1787415822764-jw0prx.webp", kind: "image", width: 1280, height: 720, caption: "Its matching 1280×720 thumbnail" },
    { uri: "/showcase/img-1787416595408-vbl2wp.webp", kind: "image", width: 1280, height: 720, caption: "A character reference sheet for the cast" },
    { uri: "/showcase/img-1787416596550-1ogxp3.webp", kind: "image", width: 1280, height: 720, caption: "A title card with the film's details" },
  ],

  tts: [
    { uri: "", kind: "text", caption: "A narration script", output: "In a world of scrap, one small key turns toward the light.", prompt: "In a world of scrap, one small key turns toward the light." },
  ],
};

/**
 * One verified example per advertised platform size.
 *
 * Every entry was generated through Text→Image at exactly the dimensions the nav menu promises,
 * and each file was checked on disk to confirm it really is that size — this table is the
 * evidence behind "exact pixels for every platform", not a restatement of it. Keyed by the same
 * `platform` and `format` values the deep links use.
 */
export interface SizeExample {
  format: string;
  width: number;
  height: number;
  uri: string;
  prompt: string;
  /** Video formats (Shorts, Reel, TikTok Video) carry a clip; omitted means a still. */
  kind?: "image" | "video";
}

/** Gallery tiles are capped at this height; below it they draw at intrinsic size. */
export const TILE_MAX_HEIGHT = 340;

/**
 * How many examples a format gets, derived rather than guessed.
 *
 * A tile keeps its true aspect and never exceeds TILE_MAX_HEIGHT, so its rendered width is
 * `min(naturalWidth, cap * ratio)` — and how many fit across the canvas follows from that. Coarse
 * ratio bands got this wrong in both directions: a 1:2.1 Pinterest pin draws only ~162px wide so
 * five fit, while a 2560×1440 banner draws ~605px so exactly one does.
 *
 * Capped at three so every format renders as one row. Sanity check against the shapes in use:
 * banner 1, avatar 2, square post 2, 4:5 post 3, 9:16 story 3, 2:3 pin 3, long pin 3.
 */
export function exampleTarget(width: number, height: number, canvasWidth = 1000, gap = 10): number {
  const rendered = Math.min(width, TILE_MAX_HEIGHT * (width / height));
  // Capped at three: a single row reads as a set, while a second row of the same thing is
  // padding. Anything that only fits one or two keeps that smaller number.
  return Math.max(1, Math.min(3, Math.floor(canvasWidth / (rendered + gap))));
}

/**
 * The one creative the generic "Social Post" page for each platform stands for.
 *
 * A platform page reached without a named format used to show every format that platform has, so
 * a 9:16 Reel, a 9:16 Story and a 1:1 post landed in one row at three different heights — which
 * reads as broken sizing rather than as a range of options. Naming the flagship keeps that page to
 * a single shape, the same way a format-specific page is already scoped to exactly its own size.
 */
export const SOCIAL_HERO_FORMAT: Record<string, string> = {
  youtube: "Thumbnail",
  instagram: "Post",
  tiktok: "Cover",
  pinterest: "Pin",
  x: "Post image",
  linkedin: "Post",
};

export const PLATFORM_SIZE_EXAMPLES: Record<string, SizeExample[]> = {
  youtube: [
    { format: "Video", width: 1280, height: 720, kind: "video", uri: "/showcase/vid-1787412608417-7ea606.mp4", prompt: "Cinematic establishing shot for a documentary: slow crane rise over a misty harbour at dawn, fishing boats rocking, gulls crossing frame, warm sunrise breaking through low cloud, gentle camera drift, 16:9 widescreen, filmic colour" },
    { format: "Shorts", width: 720, height: 1280, kind: "video", uri: "/showcase/vid-1787412715870-k88cif.mp4", prompt: "Vertical YouTube Shorts clip: a barista's hands pulling a espresso shot in close-up, crema swirling into the cup, steam rising, warm cafe light, subject centred in the middle third with clear space top and bottom for captions, punchy colour, 9:16" },
    { format: "Thumbnail", width: 1280, height: 720, uri: "/showcase/img-1787399505231-hq701r.webp", prompt: "YouTube thumbnail: one huge dramatic subject — a cracked vintage diving helmet lit by a single teal beam — filling the left two-thirds, deep black negative space on the right for a headline, extreme contrast, saturated rim light, legible as a tiny thumbnail" },
    { format: "Channel banner", width: 2560, height: 1440, uri: "/showcase/img-1787399571389-83oimf.webp", prompt: "YouTube channel banner: a wide symmetrical hero composition, a brass telescope silhouetted centre against a gradient dusk sky, generous empty sky either side so side-crops lose nothing, calm and premium" },
    { format: "Avatar", width: 800, height: 800, uri: "/showcase/img-1787402795303-us55v3.webp", prompt: "Channel avatar: a bold flat-illustrated owl head in cream and deep teal, thick geometric shapes, centred, plain charcoal ground, readable at 48 pixels" },
    { format: "Avatar", width: 800, height: 800, uri: "/showcase/img-1787399620405-tshfvb.webp", prompt: "Channel avatar: a bold flat-illustrated fox head mark in cream and burnt orange, thick clean shapes, perfectly centred, plain deep-navy ground, readable at 48 pixels" },
  ],
  instagram: [
    { format: "Reel", width: 720, height: 1280, kind: "video", uri: "/showcase/vid-1787412808627-mkem8w.mp4", prompt: "Vertical Instagram Reel: slow push-in on a linen-draped table as hands arrange dried flowers in a ceramic vase, soft window light, dust motes drifting, muted sage and cream palette, aesthetic lifestyle mood, subject centred with clear space top and bottom, 9:16" },
    { format: "Story", width: 1080, height: 1920, uri: "/showcase/img-1787399688417-lezwl1.webp", prompt: "Instagram Story: vertical fashion editorial, model in a mustard trench mid-stride against a cobalt wall, subject centred in the middle third with clear space top and bottom for UI, punchy saturated colour, film grain" },
    { format: "Post", width: 1080, height: 1080, uri: "/showcase/img-1787399727933-8u43if.webp", prompt: "Instagram feed post: overhead flat lay of a matcha latte, ceramic spoon and linen napkin on warm terrazzo, soft daylight, muted sage and cream palette, styled and scroll-stopping" },
    { format: "Post 4:5", width: 1080, height: 1350, uri: "/showcase/img-1787399801171-d75ydo.webp", prompt: "Instagram 4:5 portrait post: a potter's hands centring wet clay on a wheel, warm studio light, shallow depth of field, earthy palette, intimate lifestyle photography" },
    { format: "Profile photo", width: 320, height: 320, uri: "/showcase/img-1787399864811-ra5ql8.webp", prompt: "Profile mark: a minimal single-line leaf glyph in white on a coral gradient circle, flat, centred, crisp at small size" },
    { format: "Story", width: 1080, height: 1920, uri: "/showcase/img-1787402821453-e6x6o9.webp", prompt: "Instagram Story: a vertical shot of hands holding a steaming mug over a snowy railing, subject in the middle third, clear space top and bottom, warm against cool blue" },
    { format: "Story", width: 1080, height: 1920, uri: "/showcase/img-1787403293497-56v8vd.webp", prompt: "Instagram Story: a vertical neon-lit arcade corridor receding into the distance, single figure centred mid-frame, clear head and foot room, saturated magenta and cyan" },
    { format: "Post", width: 1080, height: 1080, uri: "/showcase/img-1787403353066-mzmyza.webp", prompt: "Instagram feed post: a top-down of a rustic sourdough loaf torn open on parchment, crumb visible, warm daylight, cream and wheat palette, square styled food photography" },
    { format: "Post 4:5", width: 1080, height: 1350, uri: "/showcase/img-1787403378042-2s02vf.webp", prompt: "Instagram 4:5 portrait post: a woman laughing in a sunlit greenhouse surrounded by ferns, natural candid moment, warm green palette, portrait framing" },
    { format: "Post 4:5", width: 1080, height: 1350, uri: "/showcase/img-1787403420344-852jrs.webp", prompt: "Instagram 4:5 portrait post: a barber finishing a fade, close portrait framing, moody warm light, textured detail, editorial lifestyle" },
    { format: "Profile photo", width: 320, height: 320, uri: "/showcase/img-1787403447106-ov3pwu.webp", prompt: "Profile mark: a white minimal mountain glyph inside a deep teal circle, flat vector, centred, crisp at small size" },
    { format: "Profile photo", width: 320, height: 320, uri: "/showcase/img-1787403474920-fxit22.webp", prompt: "Profile mark: a cream crescent-moon glyph on a violet gradient circle, flat, perfectly centred, readable tiny" },
  ],
  tiktok: [
    { format: "Video", width: 720, height: 1280, kind: "video", uri: "/showcase/vid-1787413020787-2kwe7a.mp4", prompt: "Vertical TikTok clip: a street-food wok bursting into orange flame as noodles are tossed mid-air, sparks flying, thick steam, night market neon behind, bold saturated colour, fast handheld energy, subject centred with clear space top and bottom, 9:16" },
    { format: "Cover", width: 1080, height: 1920, uri: "/showcase/img-1787401773271-f6i34x.webp", prompt: "TikTok cover: a dancer mid-spin frozen against a hot pink sweep, full-bleed vertical, bold saturated colour, subject centred with clear space top and bottom for captions" },
    { format: "Cover", width: 1080, height: 1920, uri: "/showcase/img-1787401801923-nf8dvt.webp", prompt: "TikTok cover: an overhead vertical of hands assembling a rainbow fruit platter on marble, bright even light, bold and appetising, fills the whole tall frame" },
    { format: "Profile photo", width: 200, height: 200, uri: "/showcase/img-1787403539122-l1h6jo.webp", prompt: "TikTok profile icon: a bold white flame glyph on an electric-blue circle, thick strokes, centred, unmistakable at 40 pixels" },
    { format: "Profile photo", width: 200, height: 200, uri: "/showcase/img-1787399920270-ebu69i.webp", prompt: "TikTok profile icon: a bold neon-lime lightning glyph on near-black, thick strokes, centred, unmistakable at 40 pixels" },
    { format: "Cover", width: 1080, height: 1920, uri: "/showcase/img-1787403722510-k0p2db.webp", prompt: "TikTok cover: a skateboarder mid-kickflip against a graffiti wall at golden hour, vertical, bold saturated colour, subject centred with clear space top and bottom" },
    { format: "Profile photo", width: 200, height: 200, uri: "/showcase/img-1787403656115-ggjhj7.webp", prompt: "TikTok profile icon: a bold yellow smiley face on deep purple, thick outline, centred, unmistakable at tiny size" },
  ],
  pinterest: [
    { format: "Pin", width: 1000, height: 1500, uri: "/showcase/img-1787399989168-1694fx.webp", prompt: "Pinterest pin: aspirational interior, a sunlit reading corner with a rattan chair, trailing plants and stacked books, warm neutral palette, clean upper third left open for a title overlay, vertical lifestyle photography" },
    { format: "Square pin", width: 1000, height: 1000, uri: "/showcase/img-1787397966445-ypwjl6.webp", prompt: "Pinterest square pin: three handmade beeswax candles on a pale linen cloth with dried lavender, soft shadow, minimal styled product photography, cream and honey palette" },
    { format: "Long pin", width: 1000, height: 2100, uri: "/showcase/img-1787400172315-btjpkb.webp", prompt: "Pinterest long pin: a vertical five-tier styled flat lay of a full baking mise en place — flour, butter, eggs, berries, finished tart — evenly stacked top to bottom, marble surface, bright even daylight, fills the entire tall frame" },
    { format: "Pin", width: 1000, height: 1500, uri: "/showcase/img-1787404091542-gby4nd.webp", prompt: "Pinterest pin: a styled autumn tablescape with candles and dried wheat on linen, warm amber palette, clean upper third for a title, vertical lifestyle photography" },
    { format: "Pin", width: 1000, height: 1500, uri: "/showcase/img-1787404192898-exw6z2.webp", prompt: "Pinterest pin: a cosy bedroom corner with layered neutral bedding and a trailing plant, soft morning light, vertical, calm space at the top for a title" },
    { format: "Square pin", width: 1000, height: 1000, uri: "/showcase/img-1787404218938-u0regb.webp", prompt: "Pinterest square pin: a neat flat-lay of knitting supplies — wool skeins, wooden needles, a folded swatch — on pale oak, soft daylight, square" },
    { format: "Long pin", width: 1000, height: 2100, uri: "/showcase/img-1787404286579-tua2rj.webp", prompt: "Pinterest long pin: a vertical four-step skincare routine flat-lay, products evenly stacked top to bottom on pale stone, bright even light, fills the entire tall frame" },
    { format: "Long pin", width: 1000, height: 2100, uri: "/showcase/img-1787404335349-qeuviw.webp", prompt: "Pinterest long pin: a tall vertical stack of a capsule wardrobe laid out flat — coat, knit, trousers, boots — evenly spaced on warm grey, editorial, fills the whole frame" },
  ],
  x: [
    { format: "Post image", width: 1600, height: 900, uri: "/showcase/img-1787400781219-b11kp9.webp", prompt: "X post image: a single bold idea — one bright red pushpin on a vast pale grid of identical grey pins, shot flat from above, huge negative space, minimal and instantly readable in a busy feed" },
    { format: "Card image", width: 1200, height: 628, uri: "/showcase/img-1787400808110-vw4uba.webp", prompt: "X link card: a clean desk vignette, an open laptop showing an abstract dashboard glow, a coffee cup and notebook, wide framing, soft daylight, professional and uncluttered" },
    { format: "Header", width: 1500, height: 500, uri: "/showcase/img-1787400849177-8y2dp1.webp", prompt: "X profile header: an ultra-wide abstract gradient of deep indigo into warm amber with fine grain, no subject, calm atmospheric banner, subject-free so a profile photo can overlap the left" },
    { format: "Profile photo", width: 400, height: 400, uri: "/showcase/img-1787400913488-31ptrv.webp", prompt: "Profile mark: a bold geometric origami crane folded from indigo paper, centred on a pale cream ground, flat graphic style, crisp at small size" },
    { format: "Profile photo", width: 400, height: 400, uri: "/showcase/img-1787404399385-xulfxw.webp", prompt: "Profile mark: a minimal white compass rose on a deep forest-green circle, flat graphic style, centred, crisp at small size" },
  ],
  linkedin: [
    { format: "Post", width: 1200, height: 627, uri: "/showcase/img-1787400968453-bm35c7.webp", prompt: "LinkedIn post image: three colleagues mid-discussion around a whiteboard of simple diagrams in a bright modern office, natural candid moment, wide framing, professional and warm, no text" },
    { format: "Portrait Post", width: 1080, height: 1350, uri: "/showcase/img-1787401862164-5djv1n.webp", prompt: "LinkedIn portrait post: a speaker mid-gesture at a small conference, warm natural light, shallow depth of field, professional and human, portrait framing, no text" },
    { format: "Portrait Post", width: 1080, height: 1350, uri: "/showcase/img-1787401904093-7jka82.webp", prompt: "LinkedIn portrait post: a designer reviewing printed charts pinned to a studio wall, candid over-the-shoulder framing, clean daylight, considered and calm" },
    { format: "Cover", width: 1584, height: 396, uri: "/showcase/img-1787403226089-nw4vgw.webp", prompt: "Ultra-wide professional LinkedIn profile cover: a city skyline at blue hour photographed straight on at eye level, the horizon running edge to edge as a continuous horizontal band, glass towers with warm lit windows, calm navy and amber, subject weight on the right so the left third stays quiet for a profile photo, no text, cinematic 4:1 strip" },
    { format: "Company banner", width: 1128, height: 191, uri: "/showcase/img-1787403172211-at400a.webp", prompt: "Ultra-wide letterbox banner, shot straight down the length of a long shared office desk at desk height: laptops, notebooks, coffee cups and hands typing arranged in a continuous horizontal band across the full width, warm daylight, shallow depth, nothing tall in frame, cinematic 6:1 strip, no text" },
    { format: "Portrait Post", width: 1080, height: 1350, uri: "/showcase/img-1787404467305-rr6wkn.webp", prompt: "LinkedIn portrait post: a mentor and mentee reviewing work on a laptop in a bright office corner, candid, warm daylight, professional, portrait framing" },
  ],
};


/**
 * No asset may appear in two places.
 *
 * Reusing one image across two sections made edits bleed: swapping the YouTube thumbnail also
 * changed the Channel Kit gallery, because both pointed at the same file. This runs in
 * development only and names the offender rather than leaving it to be spotted on screen.
 */
if (process.env.NODE_ENV !== "production") {
  const seen = new Map<string, string>();
  const claim = (uri: string, owner: string) => {
    if (!uri) return;
    const prior = seen.get(uri);
    if (prior && prior !== owner) {
      console.error(`[examples] ${uri} is used by both "${prior}" and "${owner}" — every section needs its own asset.`);
    } else {
      seen.set(uri, owner);
    }
  };
  for (const [tool, list] of Object.entries(TOOL_EXAMPLES)) {
    for (const e of list) { claim(e.uri, `tool:${tool}`); if (e.before) claim(e.before, `tool:${tool}`); }
  }
  for (const [plat, list] of Object.entries(PLATFORM_SIZE_EXAMPLES)) {
    for (const e of list) claim(e.uri, `platform:${plat}/${e.format}`);
  }
}
